#!/usr/bin/env bash
# Highlander script

# Outputs "I am invincible!!!" when receiving a SIGTERM signal.
trap "echo I am invincible!!!" SIGTERM

# Infinite loop, prints message every 2 seconds.
for (( ; ; )); do
  echo "To infinity and beyond"
  sleep 2
done
