#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is a multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number In a list format

a = 1
b = 100
c = 0
e = 3
f = 5
for y in {a..b}
do
  if (( y % 3 == 00 && y % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( y % 3 == 0 ))
  then
    echo "Fizz"
  elif (( y % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
