#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is a multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number In a list format

c = 0
e = 3
f = 5
for num in {1..100}
do
  if (( num % e == c && num % f == c ))
  then
    echo "FizzBuzz"
  elif (( num % e == c ))
  then
    echo "Fizz"
  elif (( num % f == c ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
