#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and sorts the data by occurrence

awk '{print $1, $9}' apache-access.log | awk '{count[$1" "$2]++} END {for (entry in count) print count[entry], entry}' | sort -nr -k1,1
