#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

x=0

while [ $x -lt 10 ]
do
  if [ $x -eq 7 ]
  then
    echo "good luck"
  elif [ $x -eq 3 ] 
  then
    echo "bad luck"
  else
    echo "Best School"
  fi
  (( x++ ))
done
