#!/usr/bin/env bash
# The clock displaying the time of 12 hours and 59 minutes

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ "$minute" -lt 60 ]; do
    echo "$minute"
    minute=$((minute + 1))
  done
  (( hour++ ))
done
