#!/bin/bash

# Define the file to check
file="school"

# Check if the file exists
if [ -e "$file" ]; then
    echo "$file file exists"
    
    # Check if the file is empty
    if [ ! -s "$file" ]; then
        echo "$file file is empty"
    else
        echo "$file file is not empty"
    fi
    
    # Check if the file is a regular file
    if [ -f "$file" ]; then
        echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
